In [2]:
import numpy as np

arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [2]:
a = np.array([1,2,3.4,"hello"])
a

array(['1', '2', '3.4', 'hello'], dtype='<U32')

In [ ]:
a = np.array([1,2,3,4,5.2])
a

array({1, 2, 3, 4, 5.2}, dtype=object)

In [8]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
l = [[1,2,3],[4,5,6],[7,8,9]]
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])