In [2]:
#how to create array using inbuild funtion 

# print zeros
import numpy as np
zeros = np.zeros((3,6))
zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [4]:
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
arr =np.full((4,3),100)
print(arr)

[[100 100 100]
 [100 100 100]
 [100 100 100]
 [100 100 100]]


In [7]:
identity = np.eye((5))
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
#creating arrys : range funtion and randon 

arr = np.arange(0,10,1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr= np.linspace(1,15,4)
arr

array([ 1.        ,  5.66666667, 10.33333333, 15.        ])

In [28]:
arr = np.random.randint(1,100,size=12)
print(arr)

[ 8 79 29 15 35 70 65 30 83 44 60 77]


In [32]:
arr = np.random.random((3,4))
print(arr)

[[0.37310072 0.6706366  0.94875633 0.21021315]
 [0.6407056  0.79005488 0.32104213 0.70134694]
 [0.97888169 0.01440553 0.43171511 0.43950051]]
