In [ ]:
import numpy as np
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
a = np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

In [5]:
a = np.zeros((2,3))
a


array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
a = np.ones((3,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
a = np.linspace(1,3,10)
a

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [ ]:
a = np.linspace(1,5,3) #linear space
a

array([1., 3., 5.])