In [ ]:
import numpy as np

np.random.rand(10) # normlization 0-1


array([0.68071792, 0.56286427, 0.17281218, 0.94552144, 0.2604755 ,
       0.37482599, 0.43877674, 0.85333177, 0.9444587 , 0.45146686])

In [8]:
np.random.randn(10) #standarlization -3 to 3

array([-2.09396396, -0.12760151, -1.15407433,  1.06524545,  0.55141518,
        1.79951286,  1.1584028 , -0.1272328 ,  0.2989712 , -1.59487918])

In [ ]:
np.random.randint(22)    #give randam integer number 

7

In [13]:
np.random.randint(10,20,5)  # 10 low value and 20 high value and 5 sizde of number 

array([13, 15, 17, 12, 17], dtype=int32)