In [ ]:
# Indexing and Slicing



In [8]:
import numpy as np

arr = np.array([10,20,30,40,50])

print(arr[0])
print(arr[-1])

10
50


In [15]:
arr =np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])


# print(arr[1])
# print(arr[0:1,0:1])
# print(arr[1:,1:])
print(arr[0:2,1:3])

[[2 3]
 [5 6]]


In [32]:
arr = np.array([[23,45,32,4,2],
                [1,56,73,33,3],
                [4,55,32,40,5],
                [88,4,22,14,2],
                [45,3,8,53,12]])
#[32,40]   
#[22,14]
print("First")
print(arr[2:4,2:4])
print()
#[2]   
#[3]
#[5]
#[2]
#[12]
print("Second")
print(arr[0:5,4:5])
print()
#[55,32,40]   
#[4,22,14]
print("thuird")
print(arr[2:4,1:4])
print()

First
[[32 40]
 [22 14]]

Second
[[ 2]
 [ 3]
 [ 5]
 [ 2]
 [12]]

thuird
[[55 32 40]
 [ 4 22 14]]

