In [1]:
import numpy as np

arr = np.array([[2,4,2],[9,4,2],[5,9,3]])
arr

array([[2, 4, 2],
       [9, 4, 2],
       [5, 9, 3]])

In [3]:
arr.min()

np.int64(2)

In [4]:
arr.max()

np.int64(9)

In [5]:
arr.sum()

np.int64(40)

In [ ]:
np.sum(arr,axis=0)  # colluom to zero axis 

array([16, 17,  7])

In [8]:
np.sum(arr,axis=1)    #row to 1 axis

array([ 8, 15, 17])

In [10]:
arr.mean()

np.float64(4.444444444444445)

In [11]:
arr.std()

np.float64(2.629368792488718)

In [ ]:
arr.argmax()  #maximum value index

np.int64(3)

In [ ]:
arr.argmin()   #minimum value index

np.int64(0)