In [4]:
import numpy as np 
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [5]:
arr.shape
arr.size

30

In [8]:
arr[0,4]

np.int64(5)

In [10]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [14]:
# arr[3:len(arr),3:len(arr)]
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [15]:
arr[2:5,1:4]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [16]:
arr[1:3,:len(arr)]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])